// @ts-check
import { defineConfig } from 'astro/config';

import tailwindcss from '@tailwindcss/vite';

// https://astro.build/config
export default defineConfig({
  site: 'https://webcamtestlive.com',

  // The sitemap is generated by src/pages/sitemap.xml.ts so that it lives at
  // /sitemap.xml — @astrojs/sitemap can only emit sitemap-index.xml.
  vite: {
    plugins: [tailwindcss()]
  }
});
