// @ts-check
import { defineConfig } from 'astro/config';

import tailwindcss from '@tailwindcss/vite';

// https://astro.build/config
export default defineConfig({
  site: 'https://webcamtestlive.com',

  // English stays unprefixed at / because it carries the existing rankings for
  // "webcam test" / "camera test" and serves the US, India and the Philippines,
  // where these queries are searched in English. The other locales are the
  // markets that search in their own language.
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'vi', 'pt-br', 'ru', 'id', 'hi'],
    routing: {
      prefixDefaultLocale: false,
      // "redirect" would bounce a missing translation to the English URL and
      // lose the locale; "rewrite" serves the English content at the localised
      // URL instead, so a partially translated page still resolves 200 under
      // its own hreflang while the rest is being filled in.
      fallbackType: 'rewrite',
    },
    fallback: {
      vi: 'en',
      'pt-br': 'en',
      ru: 'en',
      id: 'en',
      hi: 'en',
    },
  },

  // The sitemap is generated by src/pages/sitemap.xml.ts so that it lives at
  // /sitemap.xml, because @astrojs/sitemap can only emit sitemap-index.xml.
  vite: {
    plugins: [tailwindcss()]
  }
});
